spring:
  application:
    name: kcloak

  threads:
    virtual:
      enabled: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:migrations

  datasource:
    url: jdbc:postgresql://localhost:5432/kcloak
    username: kcloak
    password: kcloak
  profiles:
    active: realm

#logging:
#  level:
#    org.springframework.security: TRACE
#    org.springframework.security.oauth2: TRACE

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus