one-access:
  users:
    - username: super-admin
      email: superadmin@test1.com
      enabled: true
      first-name: super
      last-name: admin
      password: superadmin
      roles:
        - SADMIN

    - username: user1-test1
      email: user1@test1.com
      enabled: true
      first-name: user1
      last-name: test1
      password: 123
      roles:
        - USER

    - username: user2-test1
      email: user2@test1.com
      enabled: true
      first-name: user2
      last-name: test1
      password: 123
      roles:
        - USER

  roles:
    - name: SADMIN
      permissions:
        - READ_USERS
        - WRITE_USERS
        - READ_CLIENTS
        - WRITE_CLIENTS
        - READ_SETTINGS
        - WRITE_SETTINGS
        - WRITE_ROLES
        - READ_ROLES

    - name: USER

  clients:
    - client-id: "client1"
      client-secret: "client1secret"
      client-name: "test-client"
      client-authentication-methods:
        - value: client_secret_jwt
        - value: client_secret_post
        - value: client_secret_basic
      authorization-grant-types:
        - value: authorization_code
        - value: refresh_token
        - value: client_credentials
      redirect-uris:
        - "http://localhost:5000"
      post-logout-redirect-uris:
        - "http://localhost:5000"
      scopes:
        - OPENID
        - PROFILE

    - client-id: "client2"
      client-secret: "test-client"
      client-name: "Test Client"
      client-authentication-methods:
        - value: client_secret_post
        - value: client_secret_basic
      authorization-grant-types:
        - value: authorization_code
        - value: refresh_token
        - value: client_credentials
      redirect-uris:
        - "http://localhost:5000"
      scopes:
        - OPENID