### login as sadmin
POST http://localhost:8080/login
Content-Type: application/x-www-form-urlencoded

username=superadmin@test1.com&password=superadmin


###
GET http://localhost:8080/admin/roles/all/1



